const loginEP = "auth/login";
const registerEP = "auth/register";
const verifySessionEP = "auth/verify-session";
const refreshEP = "auth/refresh";
const logoutEP = "auth/logout";
const homeEP = "home";
const productsEP = "products";
const filterEP = "products/filter-options";
const wishlistEP = "wishlist";
const toggleWishlistEP = "wishlist/toggle" ;
const categoryEP = "categories/active-with-subcategories" ;
const cartEP = "cart";
const addToCartEP = "cart/add";
const updateCartItemEP = "cart/items"; // Will append /{itemId}
const getCartEP = "cart";
